#!/bin/sh
cd $PROJECT_ROOT
#1-decrypt
openssl enc -d -aes256 -base64 -in _sensitive_datas/_sensitive_datas.tar.xz.enc -out _sensitive_datas/_sensitive_datas.tar.xz
#2-show content
echo "++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "_sensitive_datas/_sensitive_datas.tar.xz contains:"
tar -tvJf _sensitive_datas/_sensitive_datas.tar.xz
#3 show help
echo "if you want to restore enter:"
echo "cd $PROJECT_ROOT && tar -xvJf _sensitive_datas/_sensitive_datas.tar.xz"