#!/bin/bash
#1-store
cd $PROJECT_ROOT
tar -cvJf _sensitive_datas/_sensitive_datas.tar.xz .vscode/launch.json ./launch-serve
#2-encrypt
openssl enc -aes256 -base64 -in _sensitive_datas/_sensitive_datas.tar.xz -out _sensitive_datas/_sensitive_datas.tar.xz.enc
#3-delete 
rm _sensitive_datas/_sensitive_datas.tar.xz